Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "main.py", line 39, in <module>
    main()
  File "main.py", line 27, in main
    damageCal.restoreFatigueLifeSamples(maxLoads=20)
  File "/home/blueman69/Documents/ProbabilisticFatigue/src/combinedModel.py", line 83, in restoreFatigueLifeSamples
    self.transformGPs()
  File "/home/blueman69/Documents/ProbabilisticFatigue/src/combinedModel.py", line 195, in transformGPs
    self.slicedTotal = sliceArrsvmap(self.SNew, self.amplitudes, self.totalN)
  File "/home/blueman69/anaconda3/envs/dataSc/lib/python3.7/site-packages/jax/_src/traceback_util.py", line 162, in reraise_with_filtered_traceback
    return fun(*args, **kwargs)
  File "/home/blueman69/anaconda3/envs/dataSc/lib/python3.7/site-packages/jax/_src/api.py", line 1488, in vmap_f
    ).call_wrapped(*args_flat)
  File "/home/blueman69/anaconda3/envs/dataSc/lib/python3.7/site-packages/jax/linear_util.py", line 168, in call_wrapped
    ans = self.f(*args, **dict(self.params, **kwargs))
  File "/home/blueman69/Documents/ProbabilisticFatigue/src/combinedModel.py", line 38, in sliceArrs
    return jnp.transpose(out)[mask]
  File "/home/blueman69/anaconda3/envs/dataSc/lib/python3.7/site-packages/jax/_src/numpy/lax_numpy.py", line 3540, in _rewriting_take
    treedef, static_idx, dynamic_idx = _split_index_for_jit(idx, arr.shape)
  File "/home/blueman69/anaconda3/envs/dataSc/lib/python3.7/site-packages/jax/_src/numpy/lax_numpy.py", line 3619, in _split_index_for_jit
    idx = _expand_bool_indices(idx, shape)
  File "/home/blueman69/anaconda3/envs/dataSc/lib/python3.7/site-packages/jax/_src/numpy/lax_numpy.py", line 3932, in _expand_bool_indices
    raise errors.NonConcreteBooleanIndexError(abstract_i)
jax._src.traceback_util.UnfilteredStackTrace: jax._src.errors.NonConcreteBooleanIndexError: Array boolean indices must be concrete; got ShapedArray(bool[180])

See https://jax.readthedocs.io/en/latest/errors.html#jax.errors.NonConcreteBooleanIndexError

The stack trace below excludes JAX-internal frames.
The preceding is the original exception that occurred, unmodified.

--------------------

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/blueman69/anaconda3/envs/dataSc/lib/python3.7/site-packages/pudb/__init__.py", line 148, in runscript
    dbg._runscript(mainpyfile)
  File "/home/blueman69/anaconda3/envs/dataSc/lib/python3.7/site-packages/pudb/debugger.py", line 514, in _runscript
    self.run(statement)
  File "/home/blueman69/anaconda3/envs/dataSc/lib/python3.7/bdb.py", line 578, in run
    exec(cmd, globals, locals)
  File "<string>", line 1, in <module>
  File "main.py", line 39, in <module>
    main()
  File "main.py", line 27, in main
    damageCal.restoreFatigueLifeSamples(maxLoads=20)
  File "/home/blueman69/Documents/ProbabilisticFatigue/src/combinedModel.py", line 83, in restoreFatigueLifeSamples
    self.transformGPs()
  File "/home/blueman69/Documents/ProbabilisticFatigue/src/combinedModel.py", line 195, in transformGPs
    self.slicedTotal = sliceArrsvmap(self.SNew, self.amplitudes, self.totalN)
  File "/home/blueman69/Documents/ProbabilisticFatigue/src/combinedModel.py", line 38, in sliceArrs
    return jnp.transpose(out)[mask]
  File "/home/blueman69/anaconda3/envs/dataSc/lib/python3.7/site-packages/jax/_src/numpy/lax_numpy.py", line 3540, in _rewriting_take
    treedef, static_idx, dynamic_idx = _split_index_for_jit(idx, arr.shape)
  File "/home/blueman69/anaconda3/envs/dataSc/lib/python3.7/site-packages/jax/_src/numpy/lax_numpy.py", line 3619, in _split_index_for_jit
    idx = _expand_bool_indices(idx, shape)
  File "/home/blueman69/anaconda3/envs/dataSc/lib/python3.7/site-packages/jax/_src/numpy/lax_numpy.py", line 3932, in _expand_bool_indices
    raise errors.NonConcreteBooleanIndexError(abstract_i)
jax._src.errors.NonConcreteBooleanIndexError: Array boolean indices must be concrete; got ShapedArray(bool[180])

See https://jax.readthedocs.io/en/latest/errors.html#jax.errors.NonConcreteBooleanIndexError
